install.packages("ggplot2", repos = getOption("repos"))
#install.packages("R6")
#install.packages("reshape2")
#install.packages("knitr")
#install.packages("rmarkdown")
#install.packages("testthat")
#install.packages("pander")
#install.packages("gridExtra")
#install.packages("readxl")
#install.packages("styler")
