name: Docker test 2
on: push

jobs:
  build:
    name: Docker tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/workflows/Dockerfile
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/base-r3.6.3-centos7:${{ github.sha }}
            docker.pkg.github.com/${{ github.repository }}/base-r3.6.3-centos7:${{ github.ref }}
