FROM rstudio/r-base:3.6.3-centos7

ENTRYPOINT ["sh"]

# Install R package dependencies
# RUN R --no-save -e "install.packages('R6', repos='http://cran.rstudio.com/')"
RUN mkdir -p /tmp_setup
COPY .github/workflows/install_packages.R /tmp_setup/install_packages.R
RUN Rscript --no-save /tmp_setup/install_packages.R

RUN rm -rf /tmp_setup