name: Docker test 3
on: 
#  release:
#    types: [published]
  push

jobs:
  prepare:
    name: Prepare Build
    runs-on: ubuntu-latest
    steps:
      - name: tag name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF##*/}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: Build images
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/workflows/Dockerfile
          push: true
          tags: |
            docker.pkg.github.com/yuri05/hello-github-actions/base-r3.6.3-centos7:${{ jobs.prepare.steps.tag_name.outputs.SOURCE_TAG}}

