name: Docker tests
on: push

jobs:
  build:
    name: Docker tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: r3.6.3:centos7
      -
        name: Inspect
        run: |
          docker image r3.6.3:centos7
